### ISSUE TITLE
how to make it

### ISSUE THREAD

**Issue by dbdxnuliba** [robotics-upo/lightsfm#1]
can you show the step how to make and install it

**Comment by dbdxnuliba** [comment]
make
g++ -c -Wall -O3  -std=gnu++11 -Iinclude  src/test.cpp -o obj/test.o
In file included from include/sfm.hpp:29:0,
                 from src/test.cpp:24:
include/vector2d.hpp:28:33: fatal error: geometry_msgs/Point.h: No such file or directory
compilation terminated.

**Comment by lmercab** [comment]
Sorry, because there is no information about the library and its dependencies. It is a header-based library, so actually to use in your projects you can install it at system level with make install. 

With make you just compile and build the test.cpp source. 

To use it you need to have installed ROS (https://www.ros.org), as it depends on different messages from ROS. Mainly geometry_msgs, but also others if you use other parts of the library.

**Comment by dbdxnuliba** [comment]
ok, I SEE
